### ISSUE TITLE
How do I do ondemand app update check?

### ISSUE THREAD

**Issue by kmspop** [microsoft/appcenter-sdk-android#1313] opened 2019-11-06 19:16 UTC
Hockeyapp used to have check for update API, which client can call to check if update is available.

With this App-center SDK, I can't find this type of API anywhere in the doc.
The problem is that our app has a screen where check for update button is present and when tapped, a progress indicator is shown until app check if completed.
Hockeyapp had all required callbacks to handle this feature.

I would like to request to add an API that checks for update on demand.

Also let's assume sending crash logs failed due to network issue.
How do we retry the send?
SDK doc doesn't explain how to send the crash logs again on onSendingFailed callback.
Will crash logs be sent automatically and periodically?

**Comment by guperrot** [comment] 2019-11-06 20:08
Hi, SDK would never trigger `onSendingFailed` callback if it's a network issue and would simply keep retrying (and also pause retries while network is offline and wait for it to become up again). In the event we keep having network issues or we have an outage on the endpoint and you restart the app, `onBeforeSending` is replayed after process restart.

When you receive `onSendingFailed`, it's a non recoverable error such as a 4XX code which means something seriously wrong happened like wrong appSecret that cannot be retried.

I'll file a bug so we put all those details in the docs.

As for the feature request on Distribute, will forward it.
There is a known work around to trigger the check again by disabling and enabling the SDK again, but regarding callbacks the only one we have is when a new release is detected to have the opportunity to replace the default dialog prompt by your own user confirmation logic.

How would you use the on demand check besides just calling 1 method to trigger it? What callback would you need in that flow?

**Comment by fabiendem** [comment] 2019-11-06 20:12
Hey,
Wrt the on-demand update check, this issue may be a duplicate of https://github.com/microsoft/appcenter/issues/1137

Also personally I had issues when disabling re-enabling it to force a check: https://github.com/microsoft/appcenter/issues/1205#issuecomment-546318788

**Comment by guperrot** [comment] 2019-11-06 20:20
Ok we can keep this ticket open to confirm the questions I asked in https://github.com/microsoft/appcenter-sdk-android/issues/1313#issuecomment-550479592 then once the questions are resolved, would close here and you can track discussion in https://github.com/microsoft/appcenter/issues/1137 after.

As for the work around, the disabled must not happen during the flow indeed to avoid side effects. It needs to be done when a flow is not already happening (no prompt pending, no API call pending, no download pending) which I realize now is not possible to monitor since we provide only the prompt callback. So yeah it's definitely a feature request for now to trigger on demand checks, you can comment and upvote in https://github.com/microsoft/appcenter/issues/1137 to get more traction on it.

**Comment by kmspop** [comment] 2019-11-06 21:57
Thanks for the quick response.
Looked like there was another similar feature request.
https://github.com/microsoft/appcenter-sdk-android/issues/1215

I was thinking of a very similar method call to the one we had in Hockeyapp.
e.g.
Distribute.checkForUpdate(Listener)

Listener {
     onUpdateAvailable(ReleaseDetail)
     noUpdateAvailable()
}

onUpdateAvailable callback is made when there's an update.
noUpdateAvailable callback is made when there's no update.
We need noUpdateAvailable callback because we need to dismiss progress indicator and make a toast notifying user that there's no update.

FYI, the app is running on a device that's on 24/7.
So we need a way to force check the update.

Questions are resolved.
Thanks!

**Comment by guperrot** [comment] 2019-11-06 22:02
Ok feedback appreciated.
However we already have that callback listener though, so would it make probably sense that the method has no parameter and we use the existing listener to call back to simplify the design, otherwise there would be 2 ways to subscribe.

**Comment by kmspop** [comment] 2019-11-06 22:57
Yes. That's OK.
You can add to the existing DistributeListener.
I was just showing an example.

**Comment by kmspop** [comment] 2019-11-07 19:04
One more issue.
Distribute and Crashes don't work when the app is side loaded.

Step to reproduce.
1. Go to AppCenter and download the APK.
2. Install the APK on a device and launch the app.
3. onReleaseAvailable is not called when there's a new version available in the App center.

Also calling Crashes.generateTestCrash() doesn't report logs to App center.
Sessions under Analytics seemed to be working fine.

I see the side loading has been fixed on the AppCenter dotnet SDK 10 days ago.
I wonder if the same thing will apply to Android SDK.

**Comment by kmspop** [comment] 2019-11-07 19:45
I spoke too soon.
The build had debug flag turned on.
Calling Distribute.setEnabledForDebuggableBuild(true); solved the issue.
I apologize for the false alarm.

**Comment by guperrot** [comment] 2019-11-07 20:37
Hi, can you open a separate issue if you have problems with crash reports (and follow the problem report template where we ask for logs)? As this one is for the feature request for manual in-app updates. Thanks in advance.

**Closed** 2019-11-15 12:54 UTC
Labels: feature request

**Comment by guperrot** [comment] 2020-03-20 18:32
On demand check for update is now available in version [3.1.0](https://github.com/microsoft/appcenter-sdk-android/releases/tag/3.1.0), please check the [documentation](https://docs.microsoft.com/en-us/appcenter/sdk/distribute/android#manually-check-for-update).

Version [3.0.0](https://github.com/microsoft/appcenter-sdk-android/releases/tag/3.0.0) had a breaking change, please also read about the [private groups](https://docs.microsoft.com/en-us/appcenter/sdk/distribute/android#use-private-distribution-group) if you update the SDK.

**Comment by ptsekov** [comment] 2020-03-28 01:57
Hello, any chance of getting onNoUpdateAvailable()/noUpdateAvailable() method being added to the DistributeListener? In certain scenarios it would be very helpful to know that the update check completed regardless of its outcome. For example one could trigger the update check on application startup and wait for it to complete before proceeding to start the main application activity. Without onNoUpdateAvailable() there is no way to tell that the update check completed if the local version is the same as the one on App Center.

**Comment by russelarms** [comment] 2020-03-30 09:15
@ptsekov we already have a feature request for it. You can vote for it so we can prioritize it:
https://github.com/microsoft/appcenter-sdk-android/issues/1215

**Comment by ptsekov** [comment] 2020-03-30 19:46
Yes, I saw it but somehow got confused that #1215 is closed. Thanks!
