### ISSUE TITLE
NPE from errorLogReport.log.getException()

### ISSUE THREAD

**Issue by Songroid** [microsoft/appcenter-sdk-android#1266] opened 2019-10-01 18:44 UTC
### **Description**

Received the following stacktrace from App Center from a customer device
```java.io.File.<init> File.java:282
com.microsoft.appcenter.crashes.Crashes$9.run Crashes.java:841
com.microsoft.appcenter.AbstractAppCenterService$4.run AbstractAppCenterService.java:306
com.microsoft.appcenter.AppCenter$7.run AppCenter.java:722
android.os.Handler.handleCallback Handler.java:789
android.os.Handler.dispatchMessage Handler.java:98
android.os.Looper.loop Looper.java:164
android.os.HandlerThread.run HandlerThread.java:65
```

### **Repro Steps**

Please list the steps used to reproduce your issue.

No known repro steps. Issue from a customer device.

### **Details**

1. Which SDK version are you using?
    2.0.0
2. Which OS version did you experience the issue on?
    Android 8.0.0
3. What device version did you see this error on?  Were you using an emulator or a physical device?
    Moto Z (2) Play
4. What third party libraries are you using?
    A lot... but with this issue no other third party lib involved
5. Please enable verbose logging for your app using `AppCenter.setLogLevel(Log.VERBOSE)` before your call to `AppCenter.start(...)` and include the logs here:
    N/A since this is from a customer device

**Comment by AnastasiaKubova** [comment] 2019-10-02 07:40
Hi, @Songroid ! Thank you for contacting us! 
Could you please share full report?

**Comment by Songroid** [comment] 2019-10-05 22:58
You mean the link to App Center console? 
Is this a possible duplicate of https://github.com/microsoft/appcenter-sdk-android/pull/1124?

**Comment by MatkovIvan** [comment] 2019-10-07 14:17
@Songroid It's hard to say that it's related or not to #1124 for now. Anyway, please try to update SDK to the latest version to avoid already fixed issues.

Regarding a report - it's about raw data from the portal. You can get it from _Reports_ tab. Select device and then click "Download" button.

**Comment by Songroid** [comment] 2019-10-07 17:10
Please let me know if this works.
[report-2518324257214699999-edca2638-6a3f-44e9-94e6-84ae4af9b6fc.txt](https://github.com/microsoft/appcenter-sdk-android/files/3698636/report-2518324257214699999-edca2638-6a3f-44e9-94e6-84ae4af9b6fc.txt)

**Comment by MatkovIvan** [comment] 2019-10-08 08:59
Thanks for the report, it added the missing details so I can confirm that this issue is a duplicate of #1124 and has already been fixed.
Please update the SDK to the latest version.

**Closed by MatkovIvan** 2019-10-08 08:59 UTC
