### ISSUE TITLE
Appcenter does not save crash logs

### ISSUE THREAD

**Issue by hprandi** [microsoft/appcenter-sdk-android#1243] opened 2019-09-06 17:23 UTC
### **Description**

I have migrated my android app from HockeyApp to AppCenter. during my tests, I noticed that it is not saving the crash logs, once a crash occurs. There is an exception showing that the log file is not even being created:

```
E/AppCenterCrashes: Error writing error log to file
    java.io.FileNotFoundException: error/16d493ff-05d9-4131-8d0e-36a0acff7dc9.json: open failed: ENOENT (No such file or directory)
at libcore.io.IoBridge.open(IoBridge.java:452)
at java.io.FileOutputStream.<init>(FileOutputStream.java:87)
        at java.io.FileOutputStream.<init>(FileOutputStream.java:72)
        at java.io.FileWriter.<init>(FileWriter.java:42)
        at com.microsoft.appcenter.utils.storage.FileManager.write(FileManager.java:140)
        at com.microsoft.appcenter.crashes.Crashes.saveErrorLogFiles(Crashes.java:1070)
        at com.microsoft.appcenter.crashes.Crashes.saveUncaughtException(Crashes.java:1059)
        at com.microsoft.appcenter.crashes.Crashes.saveUncaughtException(Crashes.java:1023)
        at com.microsoft.appcenter.crashes.UncaughtExceptionHandler.uncaughtException(UncaughtExceptionHandler.java:20)
        at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:693)
        at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:690)

```

**Comment by russelarms** [comment] 2019-09-09 14:56
Hi! I see, that you open a conversation in Intercom, so I answered you there.

**Comment by MatkovIvan** [comment] 2019-09-10 10:31
Hey @hprandi 

It looks like the base part of the path is missing somehow. It's probably related to 
https://github.com/microsoft/appcenter-sdk-android/blob/aef71abd8164d769eba6408f2a53fcee45fa07cb/sdk/appcenter/src/main/java/com/microsoft/appcenter/Constants.java#L107-L108

Could you please share the full verbose log? It would be very helpful for our investigation. Thanks

**Comment by MatkovIvan** [comment] 2019-09-16 07:43
Hi, we haven't heard from you in a while so I'm closing this issue. Please reopen/comment if it still the case for you.

**Comment by Bombo** [comment] 2022-03-16 12:35
@russelarms @MatkovIvan I'm actually seeing the same error happening.

```log
2022-03-16 12:20:38.181 24397-24397/com.myapp E/AppCenterCrashes: Error writing error log to file
    java.io.FileNotFoundException: /data/user/0/com.myapp/files/error/282ac6bd-2212-4508-bac2-355d1f55ba94.json: open failed: ENOENT (No such file or directory)
        at libcore.io.IoBridge.open(IoBridge.java:492)
        at java.io.FileOutputStream.<init>(FileOutputStream.java:236)
        at java.io.FileOutputStream.<init>(FileOutputStream.java:186)
        at java.io.FileWriter.<init>(FileWriter.java:90)
        at com.microsoft.appcenter.utils.storage.FileManager.write(FileManager.java:140)
        at com.microsoft.appcenter.crashes.Crashes.saveErrorLogFiles(Crashes.java:1160)
        at com.microsoft.appcenter.crashes.Crashes.saveUncaughtException(Crashes.java:1147)
        at com.microsoft.appcenter.crashes.Crashes.saveUncaughtException(Crashes.java:1110)
        at com.microsoft.appcenter.crashes.UncaughtExceptionHandler.uncaughtException(UncaughtExceptionHandler.java:20)
        at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1073)
        at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1068)
        at java.lang.Thread.dispatchUncaughtException(Thread.java:2203)
     Caused by: android.system.ErrnoException: open failed: ENOENT (No such file or directory)
        at libcore.io.Linux.open(Native Method)
        at libcore.io.ForwardingOs.open(ForwardingOs.java:166)
        at libcore.io.BlockGuardOs.open(BlockGuardOs.java:254)
        at libcore.io.ForwardingOs.open(ForwardingOs.java:166)
        at android.app.ActivityThread$AndroidOs.open(ActivityThread.java:7542)
        at libcore.io.IoBridge.open(IoBridge.java:478)
        at java.io.FileOutputStream.<init>(FileOutputStream.java:236) 
        at java.io.FileOutputStream.<init>(FileOutputStream.java:186) 
        at java.io.FileWriter.<init>(FileWriter.java:90) 
        at com.microsoft.appcenter.utils.storage.FileManager.write(FileManager.java:140) 
        at com.microsoft.appcenter.crashes.Crashes.saveErrorLogFiles(Crashes.java:1160) 
        at com.microsoft.appcenter.crashes.Crashes.saveUncaughtException(Crashes.java:1147) 
        at com.microsoft.appcenter.crashes.Crashes.saveUncaughtException(Crashes.java:1110) 
        at com.microsoft.appcenter.crashes.UncaughtExceptionHandler.uncaughtException(UncaughtExceptionHandler.java:20) 
        at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1073) 
        at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1068) 
        at java.lang.Thread.dispatchUncaughtException(Thread.java:2203) 
```

This happened with 4.4.1, but updating to 4.4.2 didn't change anything.

**Comment by DmitriyKirakosyan** [comment] 2022-03-21 04:03
Hi @Bombo , thank you for reaching out to us!

Please share verbose logs. You can enable it using `AppCenter.setLogLevel(Log.VERBOSE)` before your call to `AppCenter.start(...)`.

**Comment by Bombo** [comment] 2022-03-21 07:55
@DmitriyKirakosyan Sure. Here you go:
[appcenter_logs.txt](https://github.com/microsoft/appcenter-sdk-android/files/8313815/appcenter_logs.txt)

Also note that we don't have this issue on _all_ devices/users. There are the ones where crash logs still come through. Obviously it's hard to say what the ratio is, though. :)

**Comment by DmitriyKirakosyan** [comment] 2022-03-22 14:48
@Bombo , thank you for the logs!

Can you also tell more about the devices the issue can be reproduced on? Android version, manufacturer, specs, etc?
You also mentioned that it may depend on users. Does it mean that it may work for some users and fail for others while running on the same device? If so, do you find any suspicious difference between such users?

**Comment by DmitriyKirakosyan** [comment] 2022-03-23 04:14
@Bombo, Thank you for the details and have a good days off!

If anyone else faces this issue, please let us know. Any additional information would be appreciated.
It would be extremely helpful if anyone would able to reproduce this issue on a demo application and share it with us.

**Comment by DmitriyKirakosyan** [comment] 2024-03-27 08:24
As we do not have plans to fix this bug in the next year, I'm closing the issue. However, contributions are still welcome.

**Closed by DmitriyKirakosyan** 2024-03-27 08:24 UTC
Labels: support
