### ISSUE TITLE
Support for Certificate Pinner in AppCenter

### ISSUE THREAD

**Issue by yogeshbagul** [microsoft/appcenter-sdk-android#1498] opened 2021-01-13 04:52 UTC
At present, if any android application wants to implement certificate pinning for appcenter service, certificate pins has to be configured in network_security_config.xml file. [https://developer.android.com/training/articles/security-config#CertificatePinning]

We are looking for programatic way [to support dynamic pin configuration] to pin the certificate pin.

OKHTTP well know networking lib - https://square.github.io/okhttp/3.x/okhttp/okhttp3/CertificatePinner.html provides a way to programmatically handle it.

Looking for the feasibility, concern from app-center team for above ask.

**Comment by MatkovIvan** [comment] 2021-01-13 10:36
Hi @yogeshbagul,

It looks like a duplicate of https://github.com/microsoft/appcenter/issues/2037, so I'm closing it.

BTW the article from the link from your message has next note:
> Certificate Pinning is Dangerous!
Pinning certificates limits your server team's abilities to update their TLS certificates. By pinning certificates, you take on additional operational complexity and limit your ability to migrate between certificate authorities.

So, it's not entirely clear why do you need it in App Center. Could you please clarify your case and why exactly do you need it?

(let's move our further conversation to your original issue)

**Closed by MatkovIvan** 2021-01-13 10:36 UTC
Labels: feature request
