### ISSUE TITLE
CheckForUpdate via Web API succeed but fail via SDK

### ISSUE THREAD

**Issue by ms-lehaofeng** [microsoft/appcenter-sdk-android#1705] opened 2023-09-07 10:17 UTC
### **Description**
I found there is a case when execute `CheckForUpdate`. It can fail after log "Complete current updating process.". I compared the failure log with success one. If Web API call fails, there should be at least some other log after that one but there is not.
I read the source code and guess the issue should happen when calling `executeOnExecutor(AsyncTask.THREAD_POOL_EXECUTOR)` in `DefaultHttpClient`. It can throw `RejectedExecutionException` and then the whole update process will end up without any further log.

Please describe the issue you are facing using the SDK.

### **Repro Steps**

Please list the steps used to reproduce your issue.

1. Check Update via Web API call first.
2. Call `Distribute.CheckForUpdate`

### **Details**

1. Which SDK version are you using?
    - e.g. 4.4.4
3. Which OS version did you experience the issue on?
    - e.g. Android 13
4. What device version did you see this error on?  Were you using an emulator or a physical device?
    - e.g. Galaxy S21
5. What third party libraries are you using?
    - example
6. Please enable verbose logging for your app using `AppCenter.setLogLevel(Log.VERBOSE)` before your call to `AppCenter.start(...)` and include the logs here:
	Line 6301: 	Line 58230: [] 2023-08-25 10:36:31.85 [11672][2] INFO [][AppCenterLogger] AppCenterDistribute: Resetting workflow on entering foreground.
	Line 6302: 	Line 58252: [] 2023-08-25 10:36:31.86 [11672][2] INFO [][AppCenterLogger] AppCenterDistribute: Resume distribute workflow...
	Line 6304: 	Line 58254: [] 2023-08-25 10:36:31.92 [11672][2] INFO [][AppCenterLogger] AppCenterDistribute: Get latest release details...
	Line 6305: 	Line 58255: [] 2023-08-25 10:36:31.92 [11672][2] INFO [][AppCenterLogger] AppCenterDistribute: Check if we need to report release installation..
	Line 6306: 	Line 58256: [] 2023-08-25 10:36:31.92 [11672][2] INFO [][AppCenterLogger] AppCenterDistribute: New release was downloaded but not installed yet, skip reporting.
	Line 6307: 	Line 58284: [] 2023-08-25 10:36:32.01 [11672][2] INFO [][AppCenterLogger] AppCenterDistribute: Complete current updating process.
	Line 6336: 	Line 58345: [] 2023-08-25 10:36:47.36 [29563][53948] INFO [][AppCenterLogger] AppCenterDistribute: Distribute workflow will be resumed on activity resume event.

**Comment by DmitriyKirakosyan** [comment] 2023-09-11 07:34
Hi @ms-lehaofeng, thank you for getting in touch!

How frequently do you encounter this issue? Have you been able to reproduce it locally?

You mentioned the possibility of an issue during an HTTP call. However, your logs contain a line that appears to indicate otherwise:
```
Line 6306: Line 58256: [] 2023-08-25 10:36:31.92 [11672][2] INFO [][AppCenterLogger] AppCenterDistribute: New release was downloaded but not installed yet, skip reporting.
```

What AppCenter SDK version are you using? Does it happen on specific android versions/devices?

**Comment by ms-lehaofeng** [comment] 2023-09-11 08:40
Hello @DmitriyKirakosyan Thank you for the reply.

We have only received 2 reports about this issue. While we cannot repro it on our test devices.

The log you attached can only indicate the url is set and ready to fire the HTTP call.
While I think it might fail right at the HTTP call task submitted to the AsyncTask Thread Pool.

The SDK we are currently using is version 4.4.4. And the two devices are Surfact Duo2 and Samsung Galaxy. Android SDK API 12 and API 14 I think.

**Comment by DmitriyKirakosyan** [comment] 2023-09-27 09:46
Closing this issue as we cannot reproduce it.

**Closed by DmitriyKirakosyan** 2023-09-27 09:46 UTC
Labels: support
