### ISSUE TITLE
App downloaded from In-app-update won't detect another update

### ISSUE THREAD

**Issue by Mr777Nick** [microsoft/appcenter-sdk-android#1594] opened 2022-01-03 11:11 UTC
### **Description**

I've been using the in-app-update feature for about 9 months, it worked perfectly fine. then around 2-3 weeks ago when the SDK is updated to 4.4.1 and 4.4.2, the application which downloaded from within the in-app-update, won't detect future updates. There's no dialog whatsoever that says there's an update, even though it exists.

### **Repro Steps**

1. Build the current app (v1.0) and distribute it from within the App Center
2. Download the app from the App Center (v1.0), then install it
3. Build and distribute another update (v1.1)
4. Open the app (v1.0), it would detect the update, then install it, this process will work fine
5. Build and distribute another update (v1.2)
6. Open the app(v1.1), the app won't detect the update, at this point any other updates won't be detected by the app. However, if I uninstall the currently installed app, then redownload the app (v1.1) from within the App Center, the app would detect the update (v1.2) with no issues.

It seems like the download APK/Application from within the in-app-update is broken or something that causes the app to not be able to download the update.

### **Details**

1. Which SDK version are you using?
    - 4.4.2
2. Which OS version did you experience the issue on?
    - Android 11, Android 10, Android 8
3. What device version did you see this error on?  Were you using an emulator or a physical device?
    - Realme 5 Pro, Infinix Hot 10, Android Studio Emulator
4. What third party libraries are you using?
    - None added since the last App Center SDK updated
5. Please enable verbose logging for your app using `AppCenter.setLogLevel(Log.VERBOSE)` before your call to `AppCenter.start(...)` and include the logs here:
Will upload the log later. 
EDIT: [Here's the link to the log](https://yummycorp.larksuite.com/file/boxushpG6kKxIBQjEA3QERR9Grb)

**Comment by AnastasiaKubova** [comment] 2022-01-06 06:15
Hi, @Mr777Nick ! Thanks for getting in touch with us! 
I was able to reproduce your issue and will label this issue as a bug. 
I can suggest you a workaround for this issue. Please try to add the package name of your application via [this API](https://docs.microsoft.com/en-us/appcenter/sdk/other-apis/android#add-distribution-stores) before App Center start:
```
Distribute.addStores(new HashSet<String>() {
    { add("com.your.package"); }
});
```
and let me know about the results?

**Comment by Mr777Nick** [comment] 2022-01-10 04:26
> Hi, @Mr777Nick ! Thanks for getting in touch with us! I was able to reproduce your issue and will label this issue as a bug. I can suggest you a workaround for this issue. Please try to add the package name of your application via [this API](https://docs.microsoft.com/en-us/appcenter/sdk/other-apis/android#add-distribution-stores) before App Center start:
> 
> ```
> Distribute.addStores(new HashSet<String>() {
>     { add("com.your.package"); }
> });
> ```
> 
> and let me know about the results?

Hey @AnastasiaKubova, thanks for your help, the workaround does fix this issue for now, I'll keep using it until the fixed version is released. Thanks again!

**Comment by clhols** [comment] 2022-02-24 11:25
@AnastasiaKubova Isn't it worth creating a 4.2.3 release just for this fix? It seems odd that this kind of bug has been out there for so long.

**Comment by AnastasiaKubova** [comment] 2022-02-24 11:29
Hi! Thanks for getting in touch with us!
This bug has a workaround. We notify you when the fix will be released.

**Comment by clhols** [comment] 2022-02-24 11:37
But everyone updating to the newest SDK version will encounter this issue and have to find this GitHub issue and implement the workaround. It would be best if you released a new version quickly to avoid new users and updaters to experience this bug and use time and resources to debug and implement the workaround.

**Comment by fabiendem** [comment] 2022-02-24 12:29
Hey +1 to @clhols 

@AnastasiaKubova In the `CHANGELOG.md` and [releases](https://github.com/microsoft/appcenter-sdk-android/releases) could you please at least flag the versions which have this bug?
This is a critical bug. 🐛 

Consider scenarios where it's not just one or two devices to update but 100s.
Here since you can't download update, the app is "bricked". The fix is fine if you're aware of it, but once the broken SDK is part of the latest update, the app will be stuck in this state.

Cheers

**Comment by DmitriyKirakosyan** [comment] 2022-02-24 14:16
Hi @fabiendem , we've updated the `CHANGELOG.md` and Release information. Thank you!

**Comment by aballano** [comment] 2022-03-14 19:04
> Hi, @Mr777Nick ! Thanks for getting in touch with us! I was able to reproduce your issue and will label this issue as a bug. I can suggest you a workaround for this issue. Please try to add the package name of your application via [this API](https://docs.microsoft.com/en-us/appcenter/sdk/other-apis/android#add-distribution-stores) before App Center start:
> 
> ```
> Distribute.addStores(new HashSet<String>() {
>     { add("com.your.package"); }
> });
> ```
> 
> and let me know about the results?

Thank you for the workaround, unfortunately it seems this API wasn't added for the no-op version (appcenter-distribute-play) so I guess to make this work is better to stay in 4.4.1 and wait for [4.4.3](https://github.com/microsoft/appcenter-sdk-android/commit/5a174473ad65ecf2f87bfaadb0fa19876489178f)?

**Comment by TedaLIEz** [comment] 2022-03-15 05:14
This issue exists from 3.3.0, because the LOCAL_STORE filter the application's id itself, so every time the application tries to install the in-app update from itself, it will return false when we check isInstalledFromAppStore in the Distribute API, and then skip the update.
![image](https://user-images.githubusercontent.com/8800730/158311225-8988c397-eafb-4679-83ea-a722267467ff.png)
![image](https://user-images.githubusercontent.com/8800730/158311257-2f857c3a-fefc-42a1-ad7b-d0c6c355b302.png)

**Comment by sergei-fedorov** [comment] 2022-03-16 08:42
Unfortunately, in-app update is not working with MIUI optimizations enabled.
As for the issue when you are not able to install an update second time, it is a known issue. See the original thread: 
 https://github.com/microsoft/appcenter-sdk-android/issues/1594.

**Comment by DmitriyKirakosyan** [comment] 2022-03-21 03:15
Hi folks, we just released a new version with this fix included.

**Closed by DmitriyKirakosyan** 2022-03-21 03:15 UTC
Labels: bug, next-release
