### ISSUE TITLE
"App installed" alert no longer present when update installation is done

### ISSUE THREAD

**Issue by fabiendem** [microsoft/appcenter-sdk-android#1644] opened 2022-07-12 14:45 UTC
### **Description**

Previously, before appcenter-sdk-android 4.4.3+, once the update was installed, a screen or an alert (depends on the OS) would be rendered once the app is installed.
The user would then be able to tap on "Open" and the updated app would start.
This behaviour is still present in other side loading apps (Files, Google Chrome, etc.):

<img src="https://user-images.githubusercontent.com/1186282/178516816-39b0fa6a-257f-4450-a8be-e71acfaab1fd.png" width="300" /> <img src="https://user-images.githubusercontent.com/1186282/178516833-42dd1dca-d471-4c53-b51f-9869aba9ace9.png" width="300" />

You won't see an installation confirmation with appcenter-sdk-android 4.4.5, the app will close after the update, almost as if it crashed.

I am wondering if we can't bring back this behaviour. The Files app and the Google Chrome apps don't have extra permission and could render this "Open" alert.

I know that you adjusted this on purpose in your recent updates but I am wondering if something didn't get lost on the way.

Cheers!

### **Repro Steps**

Please list the steps used to reproduce your issue.

1. Install an app with the appcenter-sdk-android 4.4.5
2. Download an optional update which has the appcenter-sdk-android 4.4.5
3. Install the update

You won't see an installation confirmation, the app will close, almost as if it crashed.
Then a notification is created, and you can tap on the app icon to start the app.

### **Details**

1. Which SDK version are you using?
    - 4.4.5
2. Which OS version did you experience the issue on?
    - e.g. Android 12
5. What device version did you see this error on?  Were you using an emulator or a physical device?
    - e.g. Google Pixel 6, Lenovo M8
6. What third party libraries are you using?
    - N/A
7. Please enable verbose logging for your app using `AppCenter.setLogLevel(Log.VERBOSE)` before your call to `AppCenter.start(...)` and include the logs here:
N/A

**Comment by fabiendem** [comment] 2022-07-12 15:03
I am wondering if it's not because you immediately close the installation session when you start it:
https://github.com/microsoft/appcenter-sdk-android/blob/bad11c3410b2379bb25a30f9523cf24f30c58fb0/sdk/appcenter-distribute/src/main/java/com/microsoft/appcenter/distribute/install/session/SessionReleaseInstaller.java#L207-L208

**Comment by fabiendem** [comment] 2022-07-13 10:55
👍 thank you.
No worries, the InstallPackage API is pretty obscure and the doc difficult to grasp.

Sorry, I realized that we've been using 3.3.0 before, so 3.3.0 is my point of reference, which was using the old `ACTION_INSTALL_PACKAGE`.

If it can help: 
Google provides one example with the old [ACTION_INSTALL_PACKAGE](https://developer.android.com/reference/android/content/Intent#ACTION_INSTALL_PACKAGE): https://android.googlesource.com/platform/development/+/master/samples/ApiDemos/src/com/example/android/apis/content/InstallApk.java

and one example with the new Session API: https://android.googlesource.com/platform/development/+/master/samples/ApiDemos/src/com/example/android/apis/content/InstallApkSessionApi.java

I noticed this comment: https://android.googlesource.com/platform/development/+/master/samples/ApiDemos/src/com/example/android/apis/content/InstallApkSessionApi.java#105

I don't know if the Google Chrome or Files (which can behave as installer or delegate to some app) use one or the other API.

I have found this thread as well: https://stackoverflow.com/questions/19005213/android-package-installer-how-to-get-open-and-done-and-activity-result-bot

**Comment by fabiendem** [comment] 2022-07-19 16:23
Trying to see if it's worth waiting for the next update: would you have a rough timeline around this issue to be investigated and eventually fixed?
Thanks!

**Comment by MatkovIvan** [comment] 2022-07-19 18:41
~ETA for next release is end of Q3, but in this case it's 90% "by design". I'll do my best to investigate the root cause of it during a week.

**Comment by MatkovIvan** [comment] 2022-07-26 10:48
Okay, this dialog is [implemented](https://android.googlesource.com/platform/packages/apps/PackageInstaller/+/47fe118e0178e9d72c98073ff588ee5cf353258e/src/com/android/packageinstaller/InstallAppProgress.java) as part of `ACTION_INSTALL_PACKAGE` workflow. More of that it's might differ on different device manufacturers.
In the mentioned implementation they show this dialog only if `EXTRA_RETURN_RESULT` flag is not set. But even on current `ACTION_INSTALL_PACKAGE` implementation this flag is [used](https://github.com/microsoft/appcenter-sdk-android/blob/17507e43a56719c3f7b49638db7709a85c1675d0/sdk/appcenter-distribute/src/main/java/com/microsoft/appcenter/distribute/install/intent/IntentReleaseInstaller.java#L79) to correctly handle #1619 case.

So, it's expected and it wasn't required part before. The current version shows notification about "app installed" event (behaviour changed to mitigate #1624). Closing this thread.

**Closed by MatkovIvan** 2022-07-26 10:48 UTC
Labels: support

**Comment by fabiendem** [comment] 2022-08-09 16:41
OK thanks @MatkovIvan 👍
