### ISSUE TITLE
App crashes with OutOfMemoryError after 10-11 hours

### ISSUE THREAD

**Issue by Cheesebaron** [microsoft/appcenter-sdk-android#1464] opened 2020-10-07 10:50 UTC
### **Description**

We have a Kiosk solution deployed, where we use AppCenter for crashes etc. After the devices have been on for half a day the App often crashes with a OutOfMemoryError. Mostly after 10 to 11 hours.

### **Repro Steps**

Please list the steps used to reproduce your issue.

1. Start App and use it for 10-11 hours without restarting the App
2. Crash 💥

### **Details**

1. Which SDK version are you using?
    - 3.2.2
2. Which OS version did you experience the issue on?
    - Android 9
3. What device version did you see this error on?  Were you using an emulator or a physical device?
    - Custom Kiosk Device
4. What third party libraries are you using?
    - MvvmCross
    - AndroidX
    - Xam.Plugin.Settings
    - and MANY more
5. Please enable verbose logging for your app using `AppCenter.setLogLevel(Log.VERBOSE)` before your call to `AppCenter.start(...)` and include the logs here:

Crash log from AppCenter:

```
Package: dk.trackman.range.kiosk
Version Code: 190935
Version Name: 1.9.0
Android: 9
Android Build: PPR1.180610.011
Manufacturer: Kuori
Model: YETI2
CrashReporter Key: 24c72b78-ae23-4df5-8ed6-c3cfabdc7f67
Start Date: 2020-10-04T05:54:20.621Z
Date: 2020-10-04T17:06:20.982Z

java.lang.OutOfMemoryError: pthread_create (1040KB stack) failed: Try again
  at java.lang.Thread.nativeCreate(Thread.java:-2)
  at java.lang.Thread.start(Thread.java:733)
  at java.util.concurrent.ThreadPoolExecutor.addWorker(ThreadPoolExecutor.java:975)
  at java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1382)
  at android.os.AsyncTask.executeOnExecutor(AsyncTask.java:651)
  at com.microsoft.appcenter.http.DefaultHttpClient.callAsync(DefaultHttpClient.java:98)
  at com.microsoft.appcenter.http.HttpClientCallDecorator.run(HttpClientCallDecorator.java:54)
  at com.microsoft.appcenter.http.HttpClientNetworkStateHandler.callAsync(HttpClientNetworkStateHandler.java:49)
  at com.microsoft.appcenter.http.HttpClientCallDecorator.run(HttpClientCallDecorator.java:54)
  at com.microsoft.appcenter.http.HttpClientRetryer.callAsync(HttpClientRetryer.java:73)
  at com.microsoft.appcenter.ingestion.AppCenterIngestion.sendAsync(AppCenterIngestion.java:92)
  at com.microsoft.appcenter.channel.DefaultChannel.sendLogs(DefaultChannel.java:534)
  at com.microsoft.appcenter.channel.DefaultChannel.access$000(DefaultChannel.java:51)
  at com.microsoft.appcenter.channel.DefaultChannel$1.run(DefaultChannel.java:514)
  at android.os.Handler.handleCallback(Handler.java:873)
  at android.os.Handler.dispatchMessage(Handler.java:99)
  at android.os.Looper.loop(Looper.java:193)
  at android.app.ActivityThread.main(ActivityThread.java:6669)
  at java.lang.reflect.Method.invoke(Method.java:-2)
  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)

Thread 2:
0   dalvik.system.VMStack.getThreadStackTrace(VMStack.java:-2)
1   java.lang.Thread.getStackTrace(Thread.java:1538)
2   java.lang.Thread.getAllStackTraces(Thread.java:1588)
3   com.microsoft.appcenter.crashes.Crashes.saveUncaughtException(Crashes.java:1137)
4   com.microsoft.appcenter.crashes.Crashes.saveUncaughtException(Crashes.java:1102)
5   com.microsoft.appcenter.crashes.UncaughtExceptionHandler.uncaughtException(UncaughtExceptionHandler.java:20)
6   java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1068)
7   java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1063)
8   java.lang.Thread.dispatchUncaughtException(Thread.java:1955)

Thread 114:
0   java.lang.Object.wait(Object.java:-2)
1   java.lang.Daemons$ReferenceQueueDaemon.runInternal(Daemons.java:178)
2   java.lang.Daemons$Daemon.run(Daemons.java:103)
3   java.lang.Thread.run(Thread.java:764)

Thread 115:
0   java.lang.Object.wait(Object.java:-2)
1   java.lang.Object.wait(Object.java:422)
2   java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:188)
3   java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:209)
4   java.lang.Daemons$FinalizerDaemon.runInternal(Daemons.java:232)
5   java.lang.Daemons$Daemon.run(Daemons.java:103)
6   java.lang.Thread.run(Thread.java:764)

Thread 116:
0   java.lang.Thread.sleep(Thread.java:-2)
1   java.lang.Thread.sleep(Thread.java:373)
2   java.lang.Thread.sleep(Thread.java:314)
3   java.lang.Daemons$FinalizerWatchdogDaemon.sleepFor(Daemons.java:342)
4   java.lang.Daemons$FinalizerWatchdogDaemon.waitForFinalization(Daemons.java:364)
5   java.lang.Daemons$FinalizerWatchdogDaemon.runInternal(Daemons.java:281)
6   java.lang.Daemons$Daemon.run(Daemons.java:103)
7   java.lang.Thread.run(Thread.java:764)

Thread 123:
0   java.util.concurrent.locks.AbstractQueuedSynchronizer.doReleaseShared(AbstractQueuedSynchronizer.java:715)
1   java.util.concurrent.locks.AbstractQueuedSynchronizer.releaseShared(AbstractQueuedSynchronizer.java:1366)
2   java.util.concurrent.CountDownLatch.countDown(CountDownLatch.java:292)
3   com.microsoft.appcenter.utils.async.DefaultAppCenterFuture.complete(DefaultAppCenterFuture.java:85)
4   com.microsoft.appcenter.AbstractAppCenterService$1.run(AbstractAppCenterService.java:93)
5   com.microsoft.appcenter.AbstractAppCenterService$6.run(AbstractAppCenterService.java:346)
6   com.microsoft.appcenter.AbstractAppCenterService$4.run(AbstractAppCenterService.java:312)
7   com.microsoft.appcenter.AppCenter$7.run(AppCenter.java:757)
8   android.os.Handler.handleCallback(Handler.java:873)
9   android.os.Handler.dispatchMessage(Handler.java:99)
10  android.os.Looper.loop(Looper.java:193)
11  android.os.HandlerThread.run(HandlerThread.java:65)

Thread 125:
0   android.os.MessageQueue.nativePollOnce(MessageQueue.java:-2)
1   android.os.MessageQueue.next(MessageQueue.java:326)
2   android.os.Looper.loop(Looper.java:160)
3   android.os.HandlerThread.run(HandlerThread.java:65)

Thread 126:
0   android.os.MessageQueue.nativePollOnce(MessageQueue.java:-2)
1   android.os.MessageQueue.next(MessageQueue.java:326)
2   android.os.Looper.loop(Looper.java:160)
3   android.os.HandlerThread.run(HandlerThread.java:65)

Thread 141:
0   java.lang.Object.wait(Object.java:-2)
1   com.android.okhttp.okio.AsyncTimeout.awaitTimeout(AsyncTimeout.java:311)
2   com.android.okhttp.okio.AsyncTimeout.access$000(AsyncTimeout.java:40)
3   com.android.okhttp.okio.AsyncTimeout$Watchdog.run(AsyncTimeout.java:286)

Thread 364:
0   android.renderscript.RenderScript.nContextPeekMessage(RenderScript.java:-2)
1   android.renderscript.RenderScript$MessageThread.run(RenderScript.java:1280)

Thread 366:
0   android.os.MessageQueue.nativePollOnce(MessageQueue.java:-2)
1   android.os.MessageQueue.next(MessageQueue.java:326)
2   android.os.Looper.loop(Looper.java:160)
3   android.os.HandlerThread.run(HandlerThread.java:65)

Thread 2281:
0   java.lang.Object.wait(Object.java:-2)
1   com.android.okhttp.ConnectionPool$1.run(ConnectionPool.java:101)
2   java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
3   java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
4   java.lang.Thread.run(Thread.java:764)

Thread 3842:
0   java.lang.Object.wait(Object.java:-2)
1   java.lang.Thread.parkFor$(Thread.java:2137)
2   sun.misc.Unsafe.park(Unsafe.java:358)
3   java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:230)
4   java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitNanos(AbstractQueuedSynchronizer.java:2101)
5   java.util.concurrent.LinkedBlockingQueue.poll(LinkedBlockingQueue.java:467)
6   java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1091)
7   java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1152)
8   java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
9   java.lang.Thread.run(Thread.java:764)
```

**Comment by MatkovIvan** [comment] 2020-10-07 11:02
Hi @Cheesebaron,

Thanks for getting in touch! This log means that App Center SDK doesn't have enough memory to send Analytics data. This does NOT mean that our SDK has memory leaks and it's the root reason of your crashes. Could you please clarify why do you think that the problem is in our SDK? If it's just because the stack trace above, then I can only suggest you debug your app memory usage.

See
- [View the Java heap and memory allocations with Memory Profiler](https://developer.android.com/studio/profile/memory-profiler)
- [Understand the OutOfMemoryError Exception](https://docs.oracle.com/javase/8/docs/technotes/guides/troubleshoot/memleaks002.html)

**Comment by Cheesebaron** [comment] 2020-10-07 11:31
Yeah, I am not sure if it is actually the AppCenter SDK's fault. However, it consistently happens with a similar stack trace at around 10-11 hours of App usage.

**Comment by vvechkanov** [comment] 2020-10-08 13:08
Hi @Cheesebaron.
I agree with you this looks like not an AppCenter fault. There are plenty of possibilities why you can face OutOfMemory error. To be completely sure it is not an AppCenter problem you could create a new application, add AppCenter into it, and use it for 10-11 hours.

**Comment by vvechkanov** [comment] 2020-10-12 07:06
Hello again!
Let me close this issue for now, but feel free to reopen this or comment if you have any other questions

**Closed by vvechkanov** 2020-10-12 07:06 UTC
Labels: support
