### ISSUE TITLE
SDK crashes if the underlying Android call throws an exception (NetworkStateHelper.isAnyNetworkConnected)

### ISSUE THREAD

**Issue by mszerling-ynd** [microsoft/appcenter-sdk-android#1679] opened 2023-03-24 12:57 UTC
### **Description**

The SDK crashes if the underlying Android call throws an exception.

### **Repro Steps**

We just observed the crash occurring randomly on production for a small subset of users. 

### **Details**

1. Which SDK version are you using?
5.0.0
2. Which OS version did you experience the issue on?
Android 7.1.2
3. What device version did you see this error on?  Were you using an emulator or a physical device?
Pax A920

crashlog:
```
Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String android.net.NetworkInfo$State.name()' on a null object reference
       at android.os.Parcel.readException(Parcel.java:1698)
       at android.os.Parcel.readException(Parcel.java:1645)
       at android.net.IConnectivityManager$Stub$Proxy.getNetworkInfoForUid(IConnectivityManager.java:1270)
       at android.net.ConnectivityManager.getNetworkInfoForUid(ConnectivityManager.java:935)
       at android.net.ConnectivityManager.getNetworkInfo(ConnectivityManager.java:929)
       at com.microsoft.appcenter.utils.NetworkStateHelper.isAnyNetworkConnected(NetworkStateHelper.java:146)
       at com.microsoft.appcenter.utils.NetworkStateHelper.isNetworkConnected(NetworkStateHelper.java:132)
       at com.microsoft.appcenter.http.HttpClientNetworkStateHandler.callAsync(HttpClientNetworkStateHandler.java:48)
       at com.microsoft.appcenter.http.HttpClientCallDecorator.run(HttpClientCallDecorator.java:54)
       at com.microsoft.appcenter.http.HttpClientRetryer.callAsync(HttpClientRetryer.java:73)
       at com.microsoft.appcenter.ingestion.AbstractAppCenterIngestion.getServiceCall(AbstractAppCenterIngestion.java:81)
       at com.microsoft.appcenter.ingestion.AppCenterIngestion.sendAsync(AppCenterIngestion.java:74)
       at com.microsoft.appcenter.channel.DefaultChannel.sendLogs(DefaultChannel.java:517)
       at com.microsoft.appcenter.channel.DefaultChannel.triggerIngestion(DefaultChannel.java:500)
       at com.microsoft.appcenter.channel.DefaultChannel.access$400(DefaultChannel.java:50)
       at com.microsoft.appcenter.channel.DefaultChannel$GroupState$1.run(DefaultChannel.java:890)
       at android.os.Handler.handleCallback(Handler.java:751)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:154)
       at android.os.HandlerThread.run(HandlerThread.java:61)
```

**Comment by aleksandr-dorofeev** [comment] 2023-03-27 13:07
Hello @mszerling-ynd
Could you elaborate more on the repro steps?
Also could you share the verbose logs([documentation](https://learn.microsoft.com/en-gb/appcenter/sdk/other-apis/android#adjust-the-log-level))?

**Comment by mszerling-ynd** [comment] 2023-03-27 14:48
Hi,

as I already mentioned there are no reproduction steps we are aware of, the issue occurs randomly for a small subset of our customers on production. We only know about it because of crash reports.

Regarding enabling verbose logs that's not sth that we are willing to do for an app running on production.

I'm sorry I cannot provide more insights but I guess the stacktrace is pretty self explaining:
- Appcenter SDK calls an Android method (`android.net.ConnectivityManager.getNetworkInfo`) which internally crashes
- as the result the app crashes

Obviously crashing system calls problematic to deal with on the other hand those calls are only used by Appcenter SDK, and if it wasn't integrated with the app at all there would be no crashes.

**Comment by aleksandr-dorofeev** [comment] 2023-03-30 10:22
@mszerling-ynd
I apologize for the misunderstanding with the reproduction of the error and with the situation with the logs. We are filed bug on our internal dashboard. Will back to you once get results.

**Comment by DmitriyKirakosyan** [comment] 2023-04-20 04:59
Hi @mszerling-ynd , this looks like a bug of a specific version of android on a specific device. The docs doesn't mention that the method can throw, so I don't feel it is a good idea to wrap the call in try-catch. I checked the source code of the `ConnectivityManager.java` and related files, but couldn't find any place where it can throw an exception. Probably there is used some specific version of the service.

@mszerling-ynd , did you try to find anything similar on the internet? Having some references would help us to understand the problem better.

**Comment by mszerling-ynd** [comment] 2023-04-24 10:21
Hi,

> did you try to find anything similar on the internet? Having some references would help us to understand the problem better.

Unfortunately not. The affected device is a quite specific device (smart POS) not even a regular phone.

best

**Comment by DmitriyKirakosyan** [comment] 2023-12-12 07:58
I'm going to close this issue as fixed. Please let me know if the bug reappears.

**Closed by DmitriyKirakosyan** 2023-12-12 07:58 UTC
Labels: bug, next-release
