### ISSUE TITLE
OutOfMemoryError happening in  android 5 versions

### ISSUE THREAD

**Issue by rameshvoltella** [microsoft/appcenter-sdk-android#1328] opened 2019-11-26 04:51 UTC
### **Description**

Please describe the issue you are facing using the SDK.

> java.lang.OutOfMemoryError: OutOfMemoryError thrown while trying to throw OutOfMemoryError; no stack available

### **Details**

1. Which SDK version are you using?
    - e.g. 1.5.0
2. Which OS version did you experience the issue on?
    - e.g. Android 5.0.1 and 5.1.1
3. What device version did you see this error on?  Were you using an emulator or a physical device?
    - Galaxy S4,Redmi Note 3

**Comment by MatkovIvan** [comment] 2019-11-26 10:15
Hi @rameshvoltella,

Thanks for getting in touch!
It looks like these devices don't have enough memory for your app.
From [the doc](https://developer.android.com/reference/java/lang/OutOfMemoryError):
> `java.lang.OutOfMemoryError` thrown when the Java Virtual Machine cannot allocate an object because it is out of memory, and no more memory could be made available by the garbage collector.

Please check if an app has memory leaks or try to optimize memory usage.

I'm going to close the issue now since the problem doesn't look related to the SDK. Please comment or reopen this issue if you think that this is caused by SDK.

**Closed by MatkovIvan** 2019-11-26 10:15 UTC
Labels: support
