### ISSUE TITLE
Strange problem during in-app update

### ISSUE THREAD

**Issue by andrekiba** [Microsoft/AppCenter-SDK-Android#964] opened 2019-02-26 17:09 UTC
Hi and thanks in advance.

This is the configuration:
Xamarin Forms app that targets only android and designed to work only on one tablet model (Lenovo Tab 4 10)
Latest version of Xamarin Forms, Android Target Version 7.1 (that is the version installed on devices).

I create two apks (with incremental version) from app center build (in Release mode, with latest build stack).

I install the first one and next manually install the second as an update -> everything works perfect
I install the first one and then use in-app updates from distribution group -> the download and the installation end without error but when I restart the app (Open button from Package Installer popup) this hangs just after the splashscreen and doesn't work.

**I want to emphasize that the 2 apks are generated by the same two builds!!**

Manual update works, in-app no.
And really I can't figure out why...
It would be something related to AppCenter app settings stored in files like AppCenter.xml?
After the in-app update that breaks the app, if I go to Settings -> Apps -> MyApp and clear app data, it works again.

This is the log, it seems that it cannot find a mono library 

`` 
W/InstallAppProgress(21120): Replacing package:net.elfo.ambrogio
 I/Finsky(11806): [1] com.google.android.finsky.verifier.impl.hf.b(178): Verification complete: id=17, package_name=net.elfo.ambrogio
 I/PackageManager.DexOptimizer(1314): Running dexopt (dex2oat) on: /data/app/vmdl327724636.tmp/base.apk pkg=net.elfo.ambrogio isa=arm64 vmSafeMode=false debuggable=false target-filter=interpret-only oatDir = /data/app/vmdl327724636.tmp/oat sharedLibraries=null
 I/ActivityManager(1314): Force stopping net.elfo.ambrogio appid=10212 user=-1: installPackageLI
 I/ActivityManager(1314): Killing 23753:net.elfo.ambrogio/u0a212 (adj 101): stop net.elfo.ambrogio
 W/ActivityManager(1314): Force removing ActivityRecord{7386620 u0 net.elfo.ambrogio/.MainActivity t128}: app died, no saved state
 I/PackageManager(1314): Package net.elfo.ambrogio codePath changed from /data/app/net.elfo.ambrogio-1 to /data/app/net.elfo.ambrogio-2; Retaining data and using new
 W/PackageManager(1314): Code path for net.elfo.ambrogio changing from /data/app/net.elfo.ambrogio-1 to /data/app/net.elfo.ambrogio-2
 W/PackageManager(1314): Resource path for net.elfo.ambrogio changing from /data/app/net.elfo.ambrogio-1 to /data/app/net.elfo.ambrogio-2
 W/PackageManager(1314): Not granting permission android.permission.BLUETOOTH_PRIVILEGED to package net.elfo.ambrogio (protectionLevel=18 flags=0x3808be44)
 W/PackageManager(1314): Not granting permission android.permission.LOCATION_HARDWARE to package net.elfo.ambrogio (protectionLevel=18 flags=0x3808be44)
 W/PackageManager(1314): Not granting permission android.permission.BATTERY_STATS to package net.elfo.ambrogio (protectionLevel=50 flags=0x3808be44)
 I/ActivityManager(1314): Force stopping net.elfo.ambrogio appid=10212 user=0: pkg removed
 D/BluetoothMapAppObserver(1618): The removed package is: net.elfo.ambrogio
 D/BluetoothMapAppObserver(1618): The installed package is: net.elfo.ambrogio
 E/AccessCtrlService(0)(2943): packageName net.elfo.ambrogio
 E/AccessCtrlService(0)(2943): packageName net.elfo.ambrogio
 W/Finsky(11806): [152] com.google.android.finsky.installqueue.impl.o.b(301): Cannot find install request for net.elfo.ambrogio
 D/Launcher.Model(2454): mAllAppsList.updatePackage net.elfo.ambrogio
 D/Launcher-ResourceIcon(2454): label:Ambrogio has no build icon resource,build icon resource file name format is:net_elfo_ambrogio__aicon
 I/ChromeSync(2582): [Sync,SyncIntentOperation] Handling the intent: Intent { act=android.intent.action.PACKAGE_ADDED dat=package:net.elfo.ambrogio flg=0x4000010 cmp=com.google.android.gms/.chimera.GmsIntentOperationService (has extras) }.
 I/test dagent receiver(5340): onReceive-- packageName-----------------------> package:net.elfo.ambrogio
 I/ActivityManager(1314): START u0 {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10000000 pkg=net.elfo.ambrogio cmp=net.elfo.ambrogio/.MainActivity} from uid 10017 on display 0
 D/ActivityManager(1314): William-Debug:taskRecord =TaskRecord{51397 #130 A=net.elfo.ambrogio U=0 StackId=1 sz=1}
 I/ActivityManager(1314): Start proc 24274:net.elfo.ambrogio/u0a212 for activity net.elfo.ambrogio/.MainActivity
 D/AppIcon(1644): startTaskLoadingAnimation: net.elfo.ambrogio
 W/monodroid(24274): Trying to load sgen from: /data/app/net.elfo.ambrogio-2/lib/arm64/libmonosgen-2.0.so
 D/AppIcon(1644): stopTaskLoadingAnimation: net.elfo.ambrogio
``

**Comment by andrekiba** [comment] 2019-02-28 07:37
nothing? At least a hint or an idea? :-(

**Comment by andrekiba** [comment] 2019-02-28 11:56
could you please check if can be related to this https://github.com/xamarin/xamarin-android/issues/1395 ?

**Comment by guperrot** [comment] 2019-03-01 22:14
Can you enable AppCenter SDK verbose logging (by adding `AppCenter.LogLevel = LogLevel.Verbose before start) on the APKs and test again then share the logs?

If it's mono related, it's probably not caused by App Center SDK issue though.

**Comment by andrekiba** [comment] 2019-03-02 05:15
good morning @guperrot, yesterday I found the problem. Inside the MainActivity OnCreate method I setup AppCenter and just after that line of code a set Distribute disabled because I don’t want immediately check for updates. It seems that just after the update process managed by  PackageInstaller, if you try to await SetDistributeEnabledAsync you have a deadlock. It doesn’t happen avery time. It is inside a lifecycle callback so I tried to wrap this call using AsyncTask but also in this case it doesn’t work...and I don’t understand why. So for now I simply don’t await this call...but it would be nice to have the possibility to understand.

**Comment by guperrot** [comment] 2019-03-02 18:37
I would have asked a thread dump when the deadlock occurs but since this is a release build it won't be possible to get that.

However App Center SDK logs will help as if there is a deadlock, the last printed App Center log will give us a hint of what is happening.

Please test a special release with verbose logging enabled `AppCenter.LogLevel = LogLevel.Verbose` before AppCenter.Start and redo the test until deadlock then please share the logs.

**Comment by jwallra** [comment] 2019-03-11 21:17
Hi @andrekiba - I'm going to close this issue.  If you are able to identify the deadlock or have more information for us, just reopen the issue and we'll get back to you!

**Closed by jwallra** 2019-03-11 21:17 UTC
Labels: support
