### ISSUE TITLE
APK dowloaded can be corrupted, should check for the checksum

### ISSUE THREAD

**Issue by fabiendem** [microsoft/appcenter-sdk-android#1389] opened 2020-03-27 17:05 UTC
### **Description**

Issue already reported at https://github.com/microsoft/appcenter/issues/1428

Using AppCenter Distribute, while the download of the update will run fine, sometimes the user may get an error at installation (system level):

> Parse Error
> There was a problem parsing the package

Once this is the case, I don't think there is any way for the user to recover, apart from clearing the data of the app from the settings.

One way to prevent this is to compare the md5 checksum of the file computed server side with the checksum of the downloaded file.
If they don't match, re-trigger the download.
I have used this snippet before https://github.com/microsoft/appcenter/issues/1428#issuecomment-601337061

### **Repro Steps**

Please list the steps used to reproduce your issue.

It's near impossible to reproduce, as in the wild, but it definitely happens.
I have developed an in-house app update system before for Android as well and ran into the same issue.

### **Details**

1. Which SDK version are you using?
    -  2.3.0
2. Which OS version did you experience the issue on?
    - Android 7.1
3. What device version did you see this error on?  Were you using an emulator or a physical device?
    - Fire tablet
4. What third party libraries are you using?
    - N/A
5. Please enable verbose logging for your app using `AppCenter.setLogLevel(Log.VERBOSE)` before your call to `AppCenter.start(...)` and include the logs here:
Couldn't reproduce the issue

**Comment by olmisa** [comment] 2020-03-27 18:28
Thanks for the request @fabiendem. We will track this request.

**Comment by MatkovIvan** [comment] 2020-03-27 21:38
Hi @fabiendem , 

Thanks for bringing our attention to this, but as you already mentioned, this is a duplicate of microsoft/appcenter#1428. Let's track this feature request there.

**Closed by MatkovIvan** 2020-03-27 21:38 UTC
Labels: feature request, support
