### ISSUE TITLE
Crash reported around JobIntentService

### ISSUE THREAD

**Issue by Songroid** [microsoft/appcenter-sdk-android#1344] opened 2020-01-03 18:34 UTC
### **Description**
Crash reported on `com.microsoft.appcenter.crashes.Crashes.a` (obfuscated)
Stacktrace:
```com.microsoft.appcenter.crashes.Crashes.a
android.os.RemoteException: Remote stack trace: 
at com.android.server.job.JobServiceContext.assertCallerLocked(JobServiceContext.java:481) 
at com.android.server.job.JobServiceContext.doDequeueWork(JobServiceContext.java:359) 
at com.android.server.job.JobServiceContext$JobCallback.dequeueWork(JobServiceContext.java:160) 
at android.app.job.IJobCallback$Stub.onTransact(IJobCallback.java:83)
at android.os.Binder.execTransact(Binder.java:739) 
```

### **Repro Steps**
N/A not able to repro. We only had reports from the portal.

### **Details**

1. Which SDK version are you using?
    2.3.0
2. Which OS version did you experience the issue on?
    Android 9
3. What device version did you see this error on?  Were you using an emulator or a physical device?
    Galaxy Note10+ and others
4. What third party libraries are you using?
    App Center Android
5. Please enable verbose logging for your app using `AppCenter.setLogLevel(Log.VERBOSE)` before your call to `AppCenter.start(...)` and include the logs here:
N/A. Link to the crash report: https://appcenter.ms/orgs/Dan-McCall-Organization/apps/Salesforce-Google-Play-2/crashes/errors/801468262u/overview

Google Issue tracker: https://issuetracker.google.com/issues/63622293

**Comment by Jamminroot** [comment] 2020-01-06 08:55
Hello, @Songroid, thanks for bringing this to our sight.
From information provided it is hard to tell what is causing the problem.
Is there any chance to check whether updating to [latest version of SDK](https://github.com/microsoft/appcenter-sdk-android/releases/tag/2.5.1) helps? There has been some work done since 2.3.0 which might be related to what you are experiencing.

**Comment by Songroid** [comment] 2020-01-07 01:11
Thank you. I will give it a try.

**Comment by ilyashumihin** [comment] 2020-01-14 09:05
Hi, @Songroid!
Is there any progress?

**Comment by Songroid** [comment] 2020-01-14 18:08
Hi @ilyashumihin we are waiting for the review results of the new version. So far no update. Is it possible to move this to a waiting status?

**Comment by ilyashumihin** [comment] 2020-01-15 13:55
@Songroid let us know as soon as there is news.

**Comment by annakocheshkova** [comment] 2020-01-21 08:49
Hey I'm closing this for now, feel free to re-open once you have more info!

**Closed by annakocheshkova** 2020-01-21 08:49 UTC
Labels: support

**Comment by DmitriyKirakosyan** [comment] 2024-06-11 06:29
@paralytic123 , what AppCenter SDK version are you using? Can you reproduce this crash locally? If yes, please share the SDK [verbose logs](https://learn.microsoft.com/en-us/appcenter/sdk/other-apis/android#adjust-the-log-level).
I noticed that the crash log doesn't mention the AppCenter SDK. Could you explain why you believe it is related to the SDK?
