### ISSUE TITLE
Support Flutter

### ISSUE THREAD

**Issue by ElektrojungeAtWork** [microsoft/appcenter-sdk-android#938] opened 2019-01-28 08:24 UTC
This is a follow up from #933, where @yuecelm implicitly asked for Flutter support.

If you are asking for Flutter support in App Center, please upvote/comment on this issue.

Cheers!
Benjamin

**Comment by King-of-Spades** [comment] 2020-03-13 14:58
Same request on the main app center repo here: https://github.com/microsoft/appcenter/issues/67

I'm not sure if it's a "real" duplicate, or if it makes sense for the request to be separate based on this being the App Center Android SDK (so a more specific case)? 

Regardless I figured it's worth cross-referencing.

**Comment by hpoul** [comment] 2020-09-16 15:22
Since this is all open source, maybe somebody should just start porting it to dart/flutter - PLEASE no plugin which just wraps the android/iOS libraries. (it's a pain otherwise to support windows,linux,mac and web). I'd be interested in analytics - does anyone know if there is an API? It looks like the endpoint is 'https://in.appcenter.ms/logs' but the only documentation i could find was regarding crash reporting https://docs.microsoft.com/en-us/appcenter/diagnostics/upload-crashes not analytics?

**Comment by AnastasiaKubova** [comment] 2020-09-17 05:05
Hi! The more detailed information about App Center API you can find [here](https://docs.microsoft.com/en-us/appcenter/api-docs/) and [here](https://docs.microsoft.com/en-us/appcenter/diagnostics/using-the-diagnostics-api).

**Comment by hpoul** [comment] 2020-09-17 06:39
@AnastasiaKubova thanks, maybe I've overlooked something, but those do not seem to cover the analytics ingestion API? (I think https://in.appcenter.ms/logs ?)

To me it looks like https://openapi.appcenter.ms/ mostly covers the admnistrator tasks, rather than ingestion. 🤔

**Comment by MatkovIvan** [comment] 2020-09-17 07:25
@hpoul yep.
I guess you can refer this swagger spec copy as ref - [ingestion.yaml](https://github.com/microsoft/appcenter-sdk-dotnet/blob/3.4.1/swagger/ingestion.yaml). Also, our SDK are open source so it can be used as ref implementation.

Regarding initial topic, I know that there is community package for flutter - https://pub.dev/packages/appcenter, so you can try this one.

**Comment by hpoul** [comment] 2020-09-17 07:44
@MatkovIvan ah thanks, didn't find that swagger before.. re flutter plugin: no i can't, because those i have found are not dart implementions, but only wrappers around the ios and android libraries - but i am (also) targeting mac, windows and linux, hence my search for a dart only solution. Using platform specific libraries and all their dependencies for 5 platforms just for analytics is a bit of a challenge 😅

**Comment by anton-roos** [comment] 2021-04-27 07:31
I agree with @hpoul I can't use any of the current Flutter plugins. It is just a wrapper around the Android SDK. We need better Flutter support. Some of our clients use legacy Android devices which are Android 4.x.x. these don't work with the current Flutter plugins and the current Flutter plugins does not even throw an exception running on API Level < 21, it just silently doesn't work which is not ideal. Hence we need a proper Flutter implementation from the ground up that will work on any Flutter platform, Android, iOS, Web, MacOS and Windows. Is anyone interested in helping to develop this?

**Comment by MatkovIvan** [comment] 2021-04-27 07:53
@anton-roos - please note that starting with App Center Android SDK [4.0](https://github.com/microsoft/appcenter-sdk-android/releases/tag/4.0.0), API 21 is a minimal one. See changelog for details:
> **[Breaking change]** Bumping the minimum Android SDK version to 21 API level (Android 5.0), because old Android versions do not support root certificate authority used by App Center and would not get CA certificates updates anymore.

**Comment by anton-roos** [comment] 2021-04-27 10:27
@MatkovIvan Thanks for the response, would it work if we create a wrapper around [App Center Android SDK 3.3.1](https://github.com/microsoft/appcenter-sdk-android/releases/tag/3.3.1) or is this version no longer supported by AppCenter? Does 3.3.1 allow API level 19?

**Comment by MatkovIvan** [comment] 2021-04-27 11:12
> is this version no longer supported by AppCenter?

We do not block old versions purposefully.

> Does 3.3.1 allow API level 19?

Yes, the minimal API level was 16. But the problem is not just minimal version - as mentioned in changelog, old Android versions do not support root certificate authority used by App Center and would not get CA certificates updates anymore. So, it won't be able to establish https connection (it's enforced due to security reasons). You can manually install root certificate on the device, but still, it doesn't make old version working on all end user devices. Unfortunately, there is no good way to support Android 4.x, this is why we bumped minimal version in SDK.

**Comment by anton-roos** [comment] 2021-04-27 11:50
Thanks so much @MatkovIvan for all your feedback, it helps me understand the issue that we are having a lot more. Perhaps, if possible, could you point me in the right direction to get the root certificate installed on the Android devices? We do have control over all devices and hardware that use our app. I have done a search for installing the certificates on Android but most of them are domain specific.

We have solved this exact issue with our Flutter http service by including client.badCertificateCallback =
        ((X509Certificate cert, String host, int port) => true);
        
If there was a way to run App Center's Analytics through our own Dart http service it would have been fine, but because we are using the wrapper provided by the Flutter plugin it does it's thing. Hence the need for a native Dart SDK which we can bring into our Flutter projects. This will need to get platform specific data form Flutter, to know which platform the SDK will target as there are multiple platforms with desktop also immanent out of beta.

Thanks again for all your help.

**Comment by MatkovIvan** [comment] 2021-04-27 13:16
If you are looking for a temporary solution, then what may be possible (we haven’t tested automated way/no official support) is to stick to the old SDK and programmatically trust the new root CA "DigiCert Global Root G2". It’s temporary because there is no guarantee that it won’t be changed again in the future (i.e. if compromised like previous one or something else) and it would break this.

**Comment by anton-roos** [comment] 2021-04-27 13:42
I will give this a shot.

**Comment by anton-roos** [comment] 2021-04-27 16:57
Hi @MatkovIvan I do not know how to thank you. We are using [Flutter AppCenter Bundle](https://pub.dev/packages/flutter_appcenter_bundle) which wraps 3.2.1 and when I installed DigiCert Global Root G3 on the device it worked instantly. We now need to figure out how to install this cert programmatically with Flutter.

**Comment by DmitriyKirakosyan** [comment] 2021-11-26 08:01
I'm going to close this issue as a duplicate of https://github.com/microsoft/appcenter/issues/67, please track the progress in the main repository.

**Closed by DmitriyKirakosyan** 2021-11-26 08:01 UTC
Labels: feature request
