### ISSUE TITLE
Optional update downloaded via DownloadManager is not titled

### ISSUE THREAD

**Issue by fabiendem** [microsoft/appcenter-sdk-android#1484] opened 2020-12-07 15:56 UTC
### **Description**

With the Distribute module, when an update is optional, the Download Manager handles the download.
It shows up in the notification drawer of the device.
The downloaded item in the notification appears as `<Untitled>`:

<img src="https://user-images.githubusercontent.com/1186282/101372632-05523e00-38a4-11eb-8357-d9232c8136dd.png" width="400" />

Ideally, the item would be titled with the name of the app and the version number so it looks legit to the user.
A title/description can be added using: 

- https://developer.android.com/reference/android/app/DownloadManager.Request#setTitle(java.lang.CharSequence)
- https://developer.android.com/reference/android/app/DownloadManager.Request#setDescription(java.lang.CharSequence)

Relevant piece of code: https://github.com/microsoft/appcenter-sdk-android/blob/9e111e84fdf491a16befe2e758a94395a524123b/sdk/appcenter-distribute/src/main/java/com/microsoft/appcenter/distribute/download/manager/DownloadManagerRequestTask.java#L30-L51

### **Repro Steps**

Please list the steps used to reproduce your issue.

1. Download an optional update
2. See the Notification drawer

### **Details**

1. Which SDK version are you using?
    - 3.3.0
2. Which OS version did you experience the issue on?
    - Android 7.1
3. What device version did you see this error on?  Were you using an emulator or a physical device?
    - Fire tablet 9th gen
4. What third party libraries are you using?
    - N/A
5. Please enable verbose logging for your app using `AppCenter.setLogLevel(Log.VERBOSE)` before your call to `AppCenter.start(...)` and include the logs here:
N/A

**Comment by olmisa** [comment] 2020-12-08 11:33
Hello @fabiendem ,
thanks for using App Center. I was able to reproduce this issue. So I mark it as a bug and move to our board.
Thanks

**Comment by fabiendem** [comment] 2020-12-08 12:14
Awesome thanks 🙌

**Comment by AnastasiaKubova** [comment] 2021-03-17 11:11
Hi there! The fix has been released in the [4.1.1](https://github.com/microsoft/appcenter-sdk-android/releases/tag/4.1.1) version of App Center SDK. Please pay attention that due to the termination of `jCenter` support all our assemblies were moved to the `Maven Central` repository.

See more about migration to `Maven Central` [here](https://docs.microsoft.com/en-us/appcenter/sdk/getting-started/android#3-add-the-app-center-sdk-modules).

**Closed by AnastasiaKubova** 2021-03-17 11:11 UTC
Labels: bug, support
