### ISSUE TITLE
Callback for manually checkUpdate

### ISSUE THREAD

**Issue by bqliang** [microsoft/appcenter-sdk-android#1664] opened 2022-11-10 07:03 UTC
Is there any way to set a callback for manually checkUpdate separately? like `Distribute.checkForUpdate(checkUpdateListener)`
When the user manually checks for updates but no release available, I want to pop up a toast to remind the user. I can only set callbacks for global check updates now like `Distribute.setListener(DistributeListener)`, This is not what I want, because every time start the activity, the automatic update will run, and then the toast will pop up.

**Comment by aleksandr-dorofeev** [comment] 2022-11-10 22:56
Hello @bqliang, Thanks for getting in touch with us!
The expected behavior is the update notification on clicking the corresponding button? Could you clarify this point?

**Comment by bqliang** [comment] 2022-11-11 06:37
> Hello @bqliang, Thanks for getting in touch with us! The expected behavior is the update notification on clicking the corresponding button? Could you clarify this point?

![](https://p0.meituan.net/dpplatform/e62aa0ee734115675d2a286d95f46996146466.png)

**Comment by aleksandr-dorofeev** [comment] 2022-11-11 10:27
Unfortunately, AppCenter SDK does not have such API. However, this can be easily achieved on the app side, with using an additional flag or so. Unfortunately, at this moment I can't say that this feature will be picked up any soon due to it specific use case, so I'm closing this issue. Let's see if anyone else is interested in it.

**Closed by aleksandr-dorofeev** 2022-11-11 10:27 UTC
Labels: feature request
