### ISSUE TITLE
Unsupported Modules Detected 

### ISSUE THREAD

**Issue by PrinceRaj700** [microsoft/appcenter-sdk-android#1408] opened 2020-04-20 10:00 UTC
Unsupported Modules Detected: Compilation is not supported for following modules: app name. Unfortunately you can't have non-Gradle Java modules and Android-Gradle modules in one project.

I will all the latest versions... of all things at this time

**Comment by AnastasiaKubova** [comment] 2020-04-20 12:52
Hi, @PrinceRaj700 ! Thanks for getting in touch with us!
Could you please add more details about your issue and share reproducing steps. Also, could you please clarify what the version of SDK are you use?
In the first look, it looks like a cache issue. You can try to perform  `File -> Invalidate Caches / Restart -> Invalidate Caches & Restart`.

**Comment by AnastasiaKubova** [comment] 2020-04-24 11:58
@PrinceRaj700 we haven’t heard from you in a while so I’m closing this issue.
Feel free to reopen this issue if it isn’t resolved or you have additional questions.

**Closed by AnastasiaKubova** 2020-04-24 11:58 UTC
Labels: support
