### ISSUE TITLE
Potential crash in Distribute.java

### ISSUE THREAD

**Issue by dajarami** [microsoft/appcenter-sdk-android#1141] opened 2019-05-06 23:53 UTC
https://github.com/microsoft/AppCenter-SDK-Android/blob/2117635bb2ad1b030f15df944b6814e61e7e9c3b/sdk/appcenter-distribute/src/main/java/com/microsoft/appcenter/distribute/Distribute.java#L1619

Experienced a rare crash around isMandatoryUpdate().
Here's the stack trace:
 java.lang.RuntimeException: An error occurred while executing doInBackground() at android.os.AsyncTask$3.done(AsyncTask.java:354) at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:383) at java.util.concurrent.FutureTask.setException(FutureTask.java:252) at java.util.concurrent.FutureTask.run(FutureTask.java:271) at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167) at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641) at java.lang.Thread.run(Thread.java:764) Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean com.microsoft.appcenter.distribute.ReleaseDetails.isMandatoryUpdate()' on a null object reference at com.microsoft.appcenter.distribute.Distribute.storeDownloadRequestId(Distribute.java:1584) at com.microsoft.appcenter.distribute.DownloadTask.doInBackground(DownloadTask.java:59) at com.microsoft.appcenter.distribute.DownloadTask.doInBackground(DownloadTask.java:17) at android.os.AsyncTask$2.call(AsyncTask.java:333) at java.util.concurrent.FutureTask.run(FutureTask.java:266) ... 3 more

This was with version 1.11.2

Was this addressed in 2.0.0?

**Comment by MatkovIvan** [comment] 2019-05-07 06:52
Hi @dajarami,

Thanks for the report. It doesn't look like a known issue. I'll let you know when this will be fixed.

**Comment by guperrot** [comment] 2019-05-13 18:54
Hi @dajarami does your app have calls to `Distribute.notifyUpdateAction` and if yes can you describe how you implemented that?

**Comment by dajarami** [comment] 2019-05-13 20:26
Hey @guperrot, we're not explicitly calling `Distribute.notifyUpdateAction`, we're using the default, bare-bones implementation of:
`AppCenter.start(MainApplication.this, <appSecret>, Distribute.class);`
during our `onCreate()` of our `MainApplication.java` class of our app.

**Comment by guperrot** [comment] 2019-05-13 20:31
So you don't use `Distribute.setListener` either I suppose.
Do you have the error report on AppCenter? If yes can you download JSON and share it with us please?
How often does it happen and do you have any other contextual information that could help us understand what is happening?

**Comment by guperrot** [comment] 2019-05-16 21:19
We believe the issue is fixed by https://github.com/microsoft/appcenter-sdk-android/pull/1146 and will be part of June release.

**Comment by dajarami** [comment] 2019-05-20 20:22
Great, thanks!

**Comment by guperrot** [comment] 2019-05-20 20:48
Let's keep it open for visibility until there is a release with the fix.

**Comment by dajarami** [comment] 2019-05-20 21:08
Ok, no problem. 👍

**Comment by dajarami** [comment] 2019-05-23 20:21
We hit this crash again recently, looking forward to this update. :)

**Comment by guperrot** [comment] 2019-05-23 20:29
If you cannot wait for the June release and are ok with using an unstable release, we publish our development snapshots.

To consume them, add

```groovy
repositories {
	maven {
		url  "https://dl.bintray.com/vsappcenter/appcenter-snapshot"
	}
}
```

to the app build.gradle file.

Then use latest version (as of today `2.1.0-11+916562d07`).

Please keep in mind unstable releases can have regressions.

**Comment by dajarami** [comment] 2019-06-04 01:12
Hi, curious as to what the ETA on the June release will be?

**Comment by dajarami** [comment] 2019-06-04 01:19
Also, do you think this crash stack is related to the bug or should I open a new issue?

Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.res.Resources$Theme android.content.Context.getTheme()' on a null object reference at android.app.AlertDialog.resolveDialogTheme(AlertDialog.java:224) at android.app.AlertDialog.(AlertDialog.java:201) at android.app.AlertDialog.(AlertDialog.java:197) at android.app.AlertDialog.(AlertDialog.java:142) at android.app.ProgressDialog.(ProgressDialog.java:109) at com.microsoft.appcenter.distribute.Distribute.showDownloadProgress(Distribute.java:1757) at com.microsoft.appcenter.distribute.Distribute.enqueueDownloadOrShowUnknownSourcesDialog(Distribute.java:1559) at com.microsoft.appcenter.distribute.Distribute$5.onClick(Distribute.java:1337) at com.android.internal.app.AlertController$ButtonHandler.handleMessage(AlertController.java:184) at android.os.Handler.dispatchMessage(Handler.java:106) at android.os.Looper.loop(Looper.java:214) at android.app.ActivityThread.main(ActivityThread.java:7045) at java.lang.reflect.Method.invoke(Native Method) at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493) at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:964)

**Comment by MatkovIvan** [comment] 2019-06-04 10:32
Hi @dajarami,

We usually release the SDKs on the third week of the month.
As for the stack trace from your last message, it looks like the separate one. We'll look at it.

Thanks,
Ivan

**Comment by MatkovIvan** [comment] 2019-06-05 12:21
@dajarami Could you please share the details about the crash from your last message? Do you have reproduction steps? Did this happen only on some particular device?
This info will help us better understand the case and not only fix this particular problem, but also analyze the root cause of it and make sure that nothing else is affected.

Thanks,
Ivan

**Comment by dajarami** [comment] 2019-06-08 01:00
@MatkovIvan Seems to have occurred once on a Galaxy S8, user didn't report anything else.  I'll forward you the App Center report to see if you can make sense of it.

**Comment by MatkovIvan** [comment] 2019-06-18 11:57
Hey!
We've included fixes in the latest SDK release for this. I'm closing the issue but please reopen if you run into this again.

**Closed by MatkovIvan** 2019-06-18 11:57 UTC
Labels: bug
